SELECT *
FROM Desercion.dbo.Desercion_Clean_NNN
WHERE NOM_REGIONAL = 'REGIONAL CAUCA'
AND NOM_CENTRO = 'CENTRO AGROPECUARIO'
AND MODALIDAD_FORMACION = 'PRESENCIAL'
order by NOM_REGIONAL, MODALIDAD_FORMACION 


SELECT top(10) *
FROM Desercion.dbo.Desercion_Clean_NNN

