SELECT avg(TOTAL_APRENDICES_MATRICULADOS)
FROM Desercion.dbo.Desercion_Clean_NNN

SELECT avg(DESERTORES_AÑO_ACTUAL)
FROM Desercion.dbo.Desercion_Clean_NNN
where NOM_CENTRO = 'CENTRO AGROEMPRESARIAL'

SELECT avg(TOTAL_APRENDICES_MATRICULADOS)
FROM Desercion.dbo.Desercion_Clean_NNN
where NOM_REGIONAL = 'REGIONAL BOGOTA'
and NOM_CENTRO = 'CENTRO DE SERVICIOS FINANCIEROS' 

SELECT stdevp(TOTAL_APRENDICES_MATRICULADOS)
FROM Desercion.dbo.Desercion_Clean_NNN

SELECT avg(TOTAL_APRENDICES_MATRICULADOS), stdevp(DESERTORES_AÑO_ACTUAL)
FROM Desercion.dbo.Desercion_Clean_NNN

SELECT avg(TOTAL_APRENDICES_MATRICULADOS), stdevp(DESERTORES_AÑO_ACTUAL)
FROM Desercion.dbo.Desercion_Clean_NNN
where NOM_PROGRAMA_FORMACION = 'MERCADEO Y VENTAS'

SELECT avg(TOTAL_APRENDICES_MATRICULADOS), stdevp(DESERTORES_AÑO_ACTUAL)
FROM Desercion.dbo.Desercion_Clean_NNN
where NOM_PROGRAMA_FORMACION = 'MERCADEO Y VENTAS'
AND MODALIDAD_FORMACION = 'PRESENCIAL'