SELECT sum(TOTAL_APRENDICES_MATRICULADOS)
FROM Desercion.dbo.Desercion_Clean_NNN

SELECT sum(TOTAL_APRENDICES_MATRICULADOS)
FROM Desercion.dbo.Desercion_Clean_NNN
where NOM_REGIONAL = 'REGIONAL ATLANTICO'

SELECT sum(TOTAL_APRENDICES_MATRICULADOS)
FROM Desercion.dbo.Desercion_Clean_NNN
where NOM_REGIONAL = 'REGIONAL SANTANDER'
and NOM_PROGRAMA_FORMACION = 'GESTION EMPRESARIAL' 

SELECT count(DESERTORES_AÑO_ACTUAL)
FROM Desercion.dbo.Desercion_Clean_NNN

SELECT sum(TOTAL_APRENDICES_MATRICULADOS), COUNT(DESERTORES_AÑO_ACTUAL)
FROM Desercion.dbo.Desercion_Clean_NNN

SELECT sum(TOTAL_APRENDICES_MATRICULADOS), COUNT(DESERTORES_AÑO_ACTUAL)
FROM Desercion.dbo.Desercion_Clean_NNN
where NOM_REGIONAL = 'REGIONAL CESAR'

SELECT sum(TOTAL_APRENDICES_MATRICULADOS), COUNT(TOTAL_APRENDICES_MATRICULADOS)
FROM Desercion.dbo.Desercion_Clean_NNN
where NOM_REGIONAL = 'REGIONAL VALLE'
and NOM_PROGRAMA_FORMACION = 'MONITOREO AMBIENTAL' 